# permissions for end users to edit shardedhttpproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: shardedhttpproxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sharded-ingress-controller
    app.kubernetes.io/part-of: sharded-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: shardedhttpproxy-editor-role
rules:
- apiGroups:
  - networking.k8s.tochka.com
  resources:
  - shardedhttpproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.tochka.com
  resources:
  - shardedhttpproxies/status
  verbs:
  - get
