name: "build dev image"

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:

  build-dev-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dotfetcher/ingress-controller-sharding-operator
          tags: |
            type=raw,value=dev-{{sha}}
          labels: |
            org.opencontainers.image.title=ingress-controller-sharding-operator
            org.opencontainers.image.description=Distributes ingress objects between ingress classes (shards) in Kubernetes
            org.opencontainers.image.vendor=Joint Stock Company Tochka

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
